/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class whu_zq_gobang_JniUtils */

#ifndef _Included_whu_zq_gobang_JniUtils
#define _Included_whu_zq_gobang_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     whu_zq_gobang_JniUtils
 * Method:    AINext
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_whu_zq_gobang_JniUtils_AINext
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
